stages:
  - stage: CleanSelfHostedAgent
    displayName: "Limpeza do agente self-hosted"
    jobs:
      - job: CleanAgent
        displayName: "Limpar agente Azure Pipelines 2"
        pool:
          name: $(agent-pool)
          demands:
            - Agent.Name -equals $(agent-pool-name)
        steps:
          - script: echo "Executando no pool: $(agent-pool)"
          
          - script: |
              echo "=== Iniciando limpeza no agente $(agent-pool-name) ==="
              echo "Limpando Diretório do agente com sucesso!"
              echo "Agent: $(Agent.MachineName)"
              echo "Workspace: $(Pipeline.Workspace)"

              # Limpar workspace
              rm -rf $(Pipeline.Workspace) || true

              # Limpar Docker, se estiver usando docker
              sudo docker system prune -af || true

              echo "Limpeza concluída!"
            displayName: "Limpar workspace e docker"